-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 8,
        },
        rounding = 15,
    },
    general = {
        allow_tearing = false,
        gaps_in = 5,
        gaps_out = 10,
        resize_on_border = true,
    },
    gestures = {
        workspace_swipe_distance = 1000,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "br",
        natural_scroll = true,
        scroll_factor = 2.0,
        touchpad = {
            scroll_factor = 2.0,
        },
    },
    misc = {
        vrr = 0,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x0",
    scale = 1.2,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("zen-browser"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("foot"))
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("webstorm"))
